using System.Collections.Generic;
using plamp.Ast.Node;
using plamp.Ast.Node.Body;

namespace plamp.Ast;

/// <summary>
/// Symbol table that matches node from ast and position in source code
/// Should be generated by parser for compiler and visitors
/// If node does not exist it should throw exception
/// </summary>
public interface ISymbolTable
{
    PlampException SetExceptionToNodeAndChildren(PlampExceptionRecord exceptionRecord, NodeBase node);
    
    PlampException SetExceptionToNodeWithoutChildren(PlampExceptionRecord exceptionRecord, NodeBase node);
    
    List<PlampException> SetExceptionToChildren(PlampExceptionRecord exceptionRecord, NodeBase node);
}