namespace plamp.Native.Tokenization.Enumerations;

public enum OperatorEnum
{
    Plus,
    Minus,
    Multiply,
    Divide,
    Equals,
    NotEquals,
    Lesser,
    Greater,
    LesserOrEquals,
    GreaterOrEquals,
    And,
    Or,
    Not,
    Assign,
    PlusAndAssign,
    MinusAndAssign,
    MultiplyAndAssign,
    DivideAndAssign,
    Increment,
    Decrement,
    MemberAccess,
    Modulo,
    ModuloAndAssign,
    BitwiseOr,
    BitwiseAnd,
    Xor,
    AndAndAssign,
    OrAndAssign,
    XorAndAssign,
    None
}